image: atlassian/default-image:3

pipelines:
  pull-requests:
    "**":
      - step:
          max-time: 120
          size: 1x
          script:
            - npm test
          trigger: automatic

  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm run build
            - zip -r production.zip appspec.yml build .[^.]*
          artifacts:
            - production.zip
      - step:
          name: Upload to S3
          services:
            - docker
          script:
            - pipe: atlassian/aws-code-deploy:0.3.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                COMMAND: "upload"
                APPLICATION_NAME: $APPLICATION_NAME
                ZIP_FILE: "production.zip"
      - step:
          name: Deploy with CodeDeploy
          services:
            - docker
          script:
            - echo "Environment ${REPOSITORY_VARIABLE}"
            - pipe: atlassian/aws-code-deploy:0.3.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                COMMAND: "deploy"
                APPLICATION_NAME: $APPLICATION_NAME
                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                IGNORE_APPLICATION_STOP_FAILURES: "true"
                FILE_EXISTS_BEHAVIOR: "OVERWRITE"
                WAIT: "true"
