version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/podamium-backend
hooks:
  ApplicationStop:
    - location: .script/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: .script/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: .script/start_server.sh
      timeout: 300
      runas: root
